### ISSUE TITLE
Remove Commented Out Code and Console Logs

### ISSUE THREAD

**Issue by pertrai1** [open-source-labs/Swell#196]
I think it would be best to have commented out code and console messages not part of the packaged app. Would be best in a feature branch. Just not sure it is best to ship this out when you can have in a branch or just remove and look at history.

Very good start on the app.

**Comment by texpatnyc** [comment]
Thanks so much for your feedback pertrai1!  We will definitely implement that fix on our next build.

**Comment by abbychao** [comment]
Hi petrai1 – we've cleaned up quite a bit in our latest version! Check it out and let us know what you think!
