### ISSUE TITLE
Webpack dev server unavailable in Electron production - breaks Github auth

### ISSUE THREAD

**Issue by esclarsky** [open-source-labs/Swell#324]
- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed
- [x] I'm reporting the issue to the correct repository (for multi-repository projects)

## Expected Behavior
Github auth and read/write access for repositories should work
## Current Behavior
Webpack dev server is currently being used for Github authorization and read/write access to repositories. This means this feature will not work in production.
## Failure Information (for bugs)
Upon packaging the application, these features break. This must be addressed specifically in the environment of Electron production, where the Webpack dev server cannot be used

**Comment by nattiechan** [comment]
We have decided to remove the GitHub auth feature as of v.1.13.0, so this is now resolved.
